const router = require('express').Router();
const auth   = require('../middleware/auth');
const { listPlans, getPlan, renamePlan, toggleFavorite, deletePlan, generate, swap } = require('../controllers/meal.controller');
router.use(auth);
router.get('/',              listPlans);
router.get('/:id',           getPlan);
router.put('/:id/name',      renamePlan);
router.put('/:id/favorite',  toggleFavorite);
router.delete('/:id',        deletePlan);
router.post('/generate',     generate);
router.post('/swap',         swap);
module.exports = router;
